version: '3.1'

services:
  app:
    build: .
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
    environment:
      - URL
      - MYSQL_SERVER=db
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
      - IMAP_SERVER
      - IMAP_PORT
      - IMAP_USER
      - IMAP_PASSWORD
      - IMAP_MAILBOX
      - SMTP_SERVER
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASSWORD
      - QUERY
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_ONETIME_PASSWORD=1
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD

volumes:
  db:
