services:
  app:
    build: .
    ports:
      - "${PORT:-80}:80"
    volumes:
      - .:/var/www/html
    environment:
      - URL
      - IMAP_SERVER
      - IMAP_PORT
      - IMAP_USER
      - IMAP_PASSWORD
      - IMAP_MAILBOX
      - SMTP_SERVER
      - SMTP_PORT
      - SMTP_USER
      - SMTP_PASSWORD
      - TO
